# Generated by Django 5.0.6 on 2024-06-20 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='departmemtname',
            new_name='departmemt_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Salary',
            new_name='salary',
        ),
    ]
